davidkpiano/react-redux-form

- src/components/control-component.js
As per issue #16. An element should always update any siblings.
> An element should always update any siblings

- src/action-types.js
- src/actions/model-actions.js
- src/reducers/model-reducer.js
- test/model-actions-spec.js
history is here https://github.com/davidkpiano/react-redux-form/issues/94
> Fields initial values

- src/reducers/form-reducer.js
- test/field-actions-spec.js
Fixes #133 
Let me know if I missed any style guide points, and if the test seems sufficient.
> Fix reset form state bug

- src/components/form-component.js
- test/form-component-spec.js
Same as for ```<Field/>```
My use case is need to use custom Form from UI lib
> Allow to pass custom component into <Form>

- examples/index.html
- examples/quick-start/components/user-form.js
- examples/validation/app.js
- examples/validation/components/submit-button.js
- examples/validation/components/user-form.js
- examples/validation/index.html
- examples/validation/store.js
One thing I wanted to do in here but did not was add an error class to the input element, it seems that this isn't really straightforward without implementing a custom component and field class wrapper since the Control is responsible for re-rendering the input and it doesn't really seem very extensible through other means.
Along the way I also noticed that the Errors documentation had an incorrect code example and I made a corresponding comment in the gitbook https://davidkpiano.gitbooks.io/react-redux-form/content/errors_component.html
> Add a minimal example using validators and Errors

- package.json
- react-redux-form.d.ts
As mentioned in #103 here is the PR for the TypeScript definition file, which I've updated to 0.13.3. I added the "typings" field in package.json as well.
> Add TypeScript definition

- test/field-component-spec.js
@davidkpiano As I said - here's the extended test case that covers the scenario that was failing currently on the version that I was using (0.12.2).
Relates to #249 , which I think can be safely closed out considering both your test case and mine are passing in the current codebase.
Thanks for an awesome tool and for maintaining it this actively! BIG 👍
> Extend custom onChange function test cases

- react-redux-form.d.ts
Sorry about the newline at the end of the file, looks like the github editor does that automatically.
> Doc mistake: props.message -> props.children

- react-redux-form.d.ts
Added missed actions, types. Reformat also included to use spaces instead tabs
Please bump version for minor number (i'm trying to improve typings management in my project and remove a bunch of self written typings)
> Tsdef update

- examples/validation/components/user-form.js
- src/components/errors-component.js
- test/errors-component-spec.js
> Add parameters to error messages if provided

- src/components/control-component.js
- src/enhancers/modeled-enhancer.js
- src/immutable.js
- src/reducers/model-reducer.js
- test/control-component-spec.js
Here's my stab at making the Control component compatible with Immutable based on the strategy discussed here: [How to use with ImmutableJS? #319](https://github.com/davidkpiano/react-redux-form/issues/319).
> Immutable control component

- src/actions/field-actions.js
- src/immutable.js
- test/field-actions-spec.js
Converting the field actions to be compatible with Immutable per issue #319.
> Implement immutable strategy in field actions

- examples/immutable/app.js
- examples/immutable/components/submit-button.js
- examples/immutable/components/user-form.js
- examples/immutable/index.html
- examples/immutable/store.js
- examples/index.html
- src/actions/field-actions.js
- src/components/form-component.js
- src/immutable.js
- test/form-component-spec.js
- test/utils.js
Implemented the Form component to be compatible with Immutable per issue #319.
> Immutable form component

- src/components/control-component.js
- test/field-parser-spec.js
This addresses #446 
Wrote a test that failed. 
Fixed the code to make it pass
> Update ViewValue with Output from parser. 

- examples/immutable/components/user-form.js
- src/components/errors-component.js
- src/immutable.js
- src/utils/get-form.js
- test/errors-component-spec.js
Implemented the Errors component to be compatible with Immutable per issue #319.
NOTE: this has merged into it the changes from the immutable_form_component branch, therefore this PR depends on [this one](https://github.com/davidkpiano/react-redux-form/pull/443) being merged first.  It also makes it look like I made way more changes here than I did in this branch, so I'll comment on the stuff I really did change and once that other PR is merged this should be less noisy.
> Immutable errors

- examples/immutable/store.js
- examples/validation/store.js
- src/immutable.js
Created an immutable version of createForms and updated a couple of the examples to use it per #319.
> Immutable version of createForms

- examples/immutable/components/submit-button.js
- examples/immutable/components/user-form.js
- examples/immutable/store.js
- package.json
- src/actions/field-actions.js
- src/components/control-component.js
- src/components/errors-component.js
- src/components/field-component.js
- src/immutable.js
- src/utils/get-field-from-state.js
- src/utils/get-form.js
- src/utils/get-from-immutable-state.js
- test/combine-forms-spec.js
- test/form-component-spec.js
- test/utils-spec.js
Modified get-form to use the immutable strategy and added it to the strategy used by all other consumers per #319.
Once this is merged I think (hope) #319 may be considered fixed.
> Immutable get-form

- README.md
Changed it from the homepage to the directly to the docs
> Changed the documentation link in the readme

- react-redux-form.d.ts
Reverted typescript declaration file to the old version (the new version nuked a lot of stuff and is not functional). Added interfaces for Control, ControlProps, combineForms, and createForms. Let me know if there are more API changes from v1 that should be added. This has been working fine for me so far. Would close #453.
> Updated typescript declaration file.

- react-redux-form.d.ts
Added some types for the cases covered by the Guides in documentation.
> update typescript declaration file

- test/field-actions-spec.js
this will test the condition on which issue #500 was made
> add unit test for #500

- react-redux-form.d.ts
Adding typescript definition for LocalForm
> Add typescript definition for LocalForm (version 1.2.2)

- src/reducers/form/change-action-reducer.js
- test/model-actions-spec.js
Don't know why the build is broken, tried to bisect in my machine(mac) and all worked.
> change reducer passing parentModel to subFields. fixes #528

- react-redux-form.d.ts
- src/components/form-component.js
- test/form-component-spec.js
Pull request for #572. Still have to update type defs.
> Form validation as function + tests.

- docs/guides/validation.md
I simply copy/pasted the exemple in doc and compiler complained
> missing ")" in doc

- react-redux-form.d.ts
Was missing, copied comment from docs
> Added type def for Form onSubmitFailed

- docs/api/Control.md
I simply tried it and it works but it is missing from the docs
> add Control.textarea to available controls

- src/utils/shallow-equal.js
The previous version does not work for Date field values
> Added Date check to shallowEqual

- react-redux-form.d.ts
Was missing, copied comments from docs
> Add typedef for Fieldset component

- docs/guides/faqs.md
https://github.com/davidkpiano/react-redux-form/issues/405
> Add entry to faqs.md

- src/actions/field-actions.js
Removed isNative and console.error from `submit()` field action per conversation in https://github.com/davidkpiano/react-redux-form/issues/696.
> Removed console.error and isNative check

- docs/api/Control.md
- docs/guides/custom-controls.md
> Document mapProps receiving a function

- react-redux-form.d.ts
> Add SetErrorsOptions to types

- docs/api/Form.md
isNull has been renamed to isEmpty.
https://github.com/chriso/validator.js/commit/e33d38a26ee2f9666b319adb67c7fc0d3dea7125
> Update form docs: isNull deprecated (validator)

- react-redux-form.d.ts
add ignore, disabled, getValue, isToggle optional props
> Typescript ControlProps definition update

- assets/styles.css
- assets/styles.scss
> [Docs] Remove an unnecessary horizontal scrollbar

- examples/immutable-track/app.js
- examples/immutable-track/index.html
- examples/index.html
- src/utils/find-key.js
I struggled for months on my own project and whether or not to remove Immutable. Due to the way Immutable avoids garbage collection when updating, I decided to keep Immutable in my project. As a result, I am submitting this PR to address #846. I also added an Immutable track() example.
Please let me know if revisions are necessary.
> Bugfix: Immutable track()

- src/immutable.js
- src/utils/find-key-immutable.js
- src/utils/find-key.js
- src/utils/track.js
Fixes https://github.com/davidkpiano/react-redux-form/issues/969
> Split find-key.js to a plain javascript and immutable version

- docs/api/Control.md
> Update <Control/> docs

- docs/guides/local.md
> Update <LocalForm> docs

- README.md
https://github.com/davidkpiano/react-redux-form/issues/997
> Mention react-redux 5.x.x support for LocalForm

- docs/guides/models.md
I feel this might clarify those who are unsure how to get at the data with their own reducer. Assuming I have it right, it took me a while to work out I could do this, though close study of the createForms api page does mention it, just not with an example.
> Suggested documentation update

- docs/api/Control.md
- docs/api/Errors.md
- docs/api/actions.md
- docs/guides/compare-redux-form.md
- docs/guides/faqs.md
Fixes #721 . Also fixed missing closing tags in other doc file ( comparison with Redux Form ).
> Fix anchors and closing tags in docs as per #721

- src/native.js
Removed imports via index.js as that indirectly imports react-dom.
> Issue #722 React Native fix

- docs/guides/compare-redux-form.md
Fixes "Sync Validation" example which compares the code to redux-form #1030
> Fix "Sync Validation" example

- react-redux-form.d.ts
type corrections for model param in actions methods
> typescript definition file correction

- docs/api/Control.md
- package-lock.json
- src/components/control-component-factory.js
- test/control-component-spec.js
Relevant issue has all the info: https://github.com/davidkpiano/react-redux-form/issues/1049
This is just a first pass! Happy to make any changes you want.
> Add `render` prop to `Control` component

- react-redux-form.d.ts
Typings to [render property feature](https://github.com/davidkpiano/react-redux-form/pull/1066).
> Add Control component render property type definition

- react-redux-form.d.ts
> Fix #1160 - typescript definition uses `bool`

- docs/guides/quickstart.md
Just spotted couple broken urls on Quick Start page.
> Fix urls on guide quickstart page

- package-lock.json
- react-redux-form.d.ts
- src/native.js
should fix #1160 , and it should now build successfully
> fix import-error

- react-redux-form.d.ts
> Fix ControlProps definition
