package.json
src/reducers/form-reducer.js
src/reducers/model-reducer.js

Because `cloneDeep` always returns new data structure, so we couldn't' get the performance boost from [pure-render](https://facebook.github.io/react/docs/advanced-performance.html#shouldcomponentupdate-in-action).
If we could support "immutability" for nested data structure, It would be nice for complex(nested) form.
Full example of code: https://gist.github.com/jihchi/841ccaccb8efcdafa3b7
Preview of result:

Use "icepick" to set/merge data strcuture instead of lodash's set/merge with cloneDeep

---

src/actions/field-actions.js
src/components/field-component.js
src/components/form-component.js
src/reducers/form-reducer.js
src/utils/index.js
test/form-component-spec.js

This PR adds the `<Form />` component with the following features:
- Validation on submit:
```js
<Form model="user"
validators={{
email: (val) => isValidEmail(val),
password: (val) => isValidPassword(val)
}}
>
...
</Form>
```
- Can set keyed validators of any field, even the form itself:
```js
<Form model="user"
validators={{
'': {
passwordsMatch: (val) => val.password === val.confirmPassword
},
username: {
required: (val) => val && val.length,
length: (val) => val.length > 8
}
}}
>
...
</Form>
```
- Can run validators whenever fields are updated, and validators will only run for changed fields:
```js
<Form model="user"
validators={{ ... }}
validateOn="change"
>
```
- Will prevent `onSubmit` when form is invalid:
```js
function executeOnValidSubmit(val) {
// ... val is the form model …
```

Form Component

---

src/components/field-component.js

When I do not set ```Field.props.errors```, it will validate error and set ```valid: true```

fix validate error with blank props.errors

---

src/actions/model-actions.js
src/components/field-component.js
test/actions-spec.js
test/model-actions-spec.js

Implemented in terms of change similar to push and remove.
Wonder if this is the most efficient way to do this?  Not clear enough on exactly what icepick is doing, but I wonder if this is causing more clones than necessary?  Maybe adding direct support to the reducer to call icepick splice would be more efficient?
For the scenario where the to/from indices are out of bounds of the array I've chosen to silently ignore the action (i.e. don't call dispatch) as in the case of an empty array this seemed to cause the array's state value to end up wtih an 'undefined' entry.
Also tweaked some of the model-actions-spec tests. They were using async (done) handling which seems unncessary for these tests as there is nothing async happening? And this prevented me from writing an empty array out of …

Add action creator to move an array item from one index to another

---

src/utils/index.js
test/form-component-spec.js

This PR improves the Form component to support deep state paths. The form- and modelReducer support already this functionality but whenever such a deep state path is defined, the form component is not able to resolve them correctly. 
Code improvements are welcome, just let me know. I also thought about to inform the user with a warning if a form- or modelValue cannot be resolved? 
cheers 
Andreas
PS: And thanks again for this great piece of software :-)

support deep state paths in <Form />

---

package.json
src/components/field-component.js

When there is a `Form` with many `Field`s, change on one `Field` will cause all other `Field`s to re-render. (So there will be many warnings with [why-did-you-update](https://github.com/garbles/why-did-you-update))
Perform a shallow compare on `Field` could avoid these.

perform shallow compare to avoid unnecessarily re-render

---

package.json
webpack.config.base.js

I believe react-addons-shallow-compare should be a peerDep because it will potentially break React 0.14.x compatibility otherwise and also isn't needed if not using <Field.
I made sure all peerDeps were listed as an external. Also found a missing devDep webpack-bundle-size-analyzer

React 0.14.x react-addons-shallow-compare and externals

---

src/utils/index.js
test/errors-component-spec.js
test/utils-spec.js

I was trying to use the `<Errors />` component on a form that wasn't stored at the root of state and found that it didn't work. This was because the `utils/getFieldFromState` helper assumed that model paths were always prefixed with a single path segment, and the tests only made sure such a scenario didn't cause errors to be thrown.

Fix handling of nested fields/forms in getFieldFromState

---

src/components/control-component.js
test/field-component-spec.js

@etrepum This PR moves the prop mapping to the internal `<Control>` state, which prevents it from recreating the mapped props _unless_ the field/control is supposed to rerender, anyway.

Fixing performance issues

---

src/utils/index.js

We were getting a very confusing bug where form submissions were being prevented because rrf was checking the wrong form's validity when we had multiple active forms on a single page.
Since lodash memoize only uses the first argument as a cache key, you'd get the same form key for every form on the page even if the model being requested was different.
This caches by model *and* state, instead of just by state, keeping most of the efficiency, while avoiding the false positive cache hits.

Fix inappropriate memoize cache hits with multiple forms on a page.

---

examples/global.css
examples/index.html
examples/quick-start/app.js
examples/quick-start/components/user-form.js
examples/quick-start/index.html
examples/quick-start/store.js
examples/server.js
examples/webpack.config.js
package.json

Add a runnable `npm run examples` server for live examples of rrf, starting with the quick-start example.
Used https://github.com/reactjs/react-router/tree/master/examples as a template.

Add a runnable `npm run examples` server

---

react-redux-form.d.ts

I realized after updating to the version with the .d.ts included that it wasn't working due to being wrapped in `declare module 'react-redux-form'` so I removed it and it now works fine in my project (same as before when I was manually referencing the .d.ts I was maintaining locally). 
Unfortunately we lose the declaration for react-redux-form/lib/immutable. If anybody knows how we could use the package.json "typings" to define multiple library files, that would be helpful.

Remove .d.ts 'declare module,' TS definitions are now top-level

---

src/utils/index.js

It seems that `formStateKeyCaches` wasn't caching because the [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) methods were being used on `state` rather than the `model` key.

Fix form state caching

---

immutable.d.ts
package.json
react-redux-form.d.ts

* Fixed case when noImplicitAny used in TS 
* Added missed lib/immutable definition
immutable.d.ts should be placed on lib/ to allow compiler pickup correct file when ```import "react-redux-form/lib/immutable```, thus i added prepublish step to package.json which copying immutable.d.ts file to lib. Not sure if this solution is cross-platform

Typescript definition update

---

package.json
webpack.config.base.js
webpack.config.prod.js

#334 
This is just one possible solution.
The current react-redux-form build has a webpack.config.base.js and a webpack.config.prod.js.
It wasn't clear to me what the goal of these two configs were, but the issue I was having with the umd build seemed to be related to having duplicated output sections and also specifying the output file both on the command line (in package.json) and in the prod output section.
So I removed the prod output section.  I also had to rename the output lib to 'ReactReduxForm' from 'react-redux-form' as I had an issue referencing a name with hyphens in my own project's webpack externals.  But that could be because I am doing it wrong.

Possible fixes for umd build

---

src/utils/deep-compare-children.js

React.Children.toArray filters out `false` children, so it can't
be assumed that lengths are the same afterwards, if children length
was equal.
I couldn't see any unit tests for this file unfortunately, but an example of something that breaks this would be changing the `showOne` `showTwo` props of the following:
```javascript
render() {
return (<Form>
{this.props.showOne && <div>One is shown</div>}
{this.props.showTwo && <div>Two is shown</div>}
</Form>)
}
```

v1 Fix deep-compare-children for `false` children.

---

src/components/form-component.js
test/form-component-spec.js

The Form component previously was using the old validators / errors props when they changed to check validation.
Swapped to using the new validators and errors props for checking new validation on props changes.
This helps somewhat with #346 but doesn't cover the full picture.

Handle Form validators / errors props changing.

---

src/components/form-component.js
test/form-component-spec.js

The Form component previously was using the old validators / errors props when they changed to check validation.
Swapped to using the new validators and errors props for checking new validation on props changes.
( #377 but for v1 beta)

v1 Handle Form validators / errors props changing.

---

examples/validation/components/user-form.js

Fixed error in Validation example where message key was not finding a match in the errors object

Fixed error in Validation example

---

docs/api/Errors.md

The example of making a component with a function referenced a messages prop which does not exist, the correct prop is 'children'

Fixed incorrect prop in error docs

---

src/components/form-component.js

I was looking for a way to use global form state in my custom form component
Digging through the sources I found, that Form's children can be a function and it worked!
However, React complains, that children must be a node. Here's a fix for that

Form children can accept function

---

src/components/form-component.js
test/form-component-spec.js

Fixes to validation of deep values on submit

Deep validation on submit

---

react-redux-form.d.ts

Made this change but some props doesn't seem to be working on Field (`mapProps` and `controlProps`) see https://esnextb.in/?gist=94a56fd57256d44909c7cb2912fecdb6 it gives some errors on the console.
If they are not supposed to be used with `Field` I have to change the typings and the documentation should be updated.
Also found the property `componentMap` that isn't used anymore (https://github.com/davidkpiano/react-redux-form/blob/master/src/components/field-component.js#L57)

Typescript FieldProps extends ControlPropsextends HTMLProps. Fixes #552

---

react-redux-form.d.ts

UpdateOn and ValidateOn also allow an array of change, blur and/or focus.

Typescript ControlProps UpdateOn/ValidateOn Fixes

---

src/utils/path-starts-with.js
src/utils/to-path.js

Does not build on linux which has case sensitive paths. I'm guessing you develop on Mac.

linux: fix topath import

---

src/components/control-component.js
src/reducers/form-actions-reducer.js
test/control-component-spec.js
test/field-component-spec.js

I noticed your PR just now.  Unfortunately it does not fix the issue since componentWillUnmount is still calling `setValidity` and not `resetValidity`.  I changed that, but then I had to make a change to the reducer to accommodate the omitKeys parameter.  If you omit keys, it's possible that the remaining validators are still invalid, so we don't want to set the field to `true` without checking.
It took me a while, but I made a test case that demonstrates the issue I am seeing.
#580

tweaks to resetValidity

---

src/reducers/form-actions-reducer.js
test/form-component-spec.js

There is a bug in this. If you have both a field validator and a form validator that outputs validation for a field, the field level will replace the form level.
I have added a failing test case.
I think this would have to be handled in the reducer? Could make a change to run merge over the two objects to set only validations that have changed in the dispatch. Thoughts?

Field level validation replaces form level validation for same field.

---

package.json
src/utils/deep-compare-children.js

This fixes a minor [preact-compat](https://github.com/developit/preact-compat) compatibility issue
* adds `shallow-compare` to package.json
* changes `react/lib/shallowCompare` to `shallow-compare` imports

Add shallowCompare to fix preact-compability

---

react-redux-form.d.ts

Without an explicit type, it is implicitly defined as any. This breaks code which depends on
react-redux-form and has the `noImplicitAny` tsc flag enabled.

Explicitly type argument of getRef

---

docs/api/actions.md

`actions.push` was missing from the table of contents of the model action creators documentation page (https://davidkpiano.github.io/react-redux-form/docs/api/actions.html)

Add actions.push to table of contents

---

docs/api/formReducer.md

1. Add missing `[options]` argument to signature
2. Fix `options` markdown in argument description

Fix options description in formReducer API doc

---

package.json

Hi, I am using this package in an existing project along with ReactBoilerplate. After trying to run a build and it failing, I did a bit of digging and found the shallow compare package version to be the issue.
Updating the latest version fixes this issue.
The issue is also discussed here: https://github.com/react-boilerplate/react-boilerplate/issues/1690

Updated to latest version of shallow-compare

---

src/components/control-component.js
src/utils/resolve-model.js

We use RRF extensively at Clover Health, and we are starting to hit performance problems on really big forms. (We have health assessment forms that span several hundred questions). I did a basic performance trace using `react-addons-perf` and found that RRF itself is responsible for a lot of render calls that don't end up touching the DOM. So, I decided to take a stab at fixing these unnecessary renders.
I created a test harness of sorts here:
https://github.com/danielericlee/rrf-perf-test-harness
This is a very simple React app created via create-react-app that attaches `react-addons-perf` to a global called `window.Perf`. It creates 500 `Control.text`'s. My "benchmark" is as follows:
1. Open the console and call `Perf.start()`.
2. Click into the first text input.
3. Type "This is a …

Perf improvements

---

src/components/field-component.js
src/components/form-component.js

While attempting to upgrade to 1.11.0 (we're several months behind currently) we sometimes get an exception after submitting a Form. 
```
Uncaught TypeError: Cannot use 'in' operator to search for 'lastSubmitEvent' in undefined
at n (index.js:5)
at t.default (index.js:12)
at o (deep-compare-children.js:59)
at r.value (form-component.js:183)
at f.updateComponent (ReactCompositeComponent.js:628)
at f.performUpdateIfNecessary (ReactCompositeComponent.js:561)
at Object.performUpdateIfNecessary (ReactReconciler.js:157)
at s (ReactUpdates.js:150)
at r.perform (Transaction.js:140)
at i.perform (Transaction.js:140)
at i.perform (ReactUpdates.js:89)
at Object.C [as flushBatchedUpdates] (ReactUpdates.js:172)
at r.closeAll (Transaction.js:206)
at r.perform (Transaction.js:153)
at …
```

Pass nextState to deepCompareChildren

---

react-redux-form.d.ts

I added the following actions to the typings:
These are still missing:
I don't have any plans to add the rest, unfortunately I don't have time at the moment.

Add some missing actions

---

docs/api/modelReducer.md
src/reducers/model-reducer.js

Internally the `actions.load` action creator is a specialized case of `actions.change`.

Remove references to nonexistent actionTypes.LOAD

---

react-redux-form.d.ts

This is necessary for the 'show' prop of the Errors component.

Update typings to make FieldState props optional

---

src/components/control-component.js
test/control-component-spec.js

The `createEventHandler` function in Control component was caching all the props on component mount, and was calling event handlers with invalid props, if they were modified by user.

Fixed a bug with dynamic props in Control component

---

src/components/control-component.js
src/utils/resolve-model.js
test/model-resolving-spec.js

This fixed the case when the model dynamically changes in the middle of the chain - for example, you were using deep `Fieldset` hierarchy, and any of them had dynamic model
The problem is caused by the fact that resolveModel decorator, that is used internally to allow partial models, was caching model value upon mounting, thus preventing it from updating properly.
I've also removed several performance optimizations, as they were also preventing context updates. I'm open to any way this could be done better.

Fixed deeply dynamic model support

---

src/components/field-component.js

`storeSubscription` passed down to `<div>` created by Field component
https://github.com/davidkpiano/react-redux-form/issues/698

Avoid storeSubscription from being passed down as props to Field

---

react-redux-form.d.ts

With recent react TS definition, components with void type parameters cannot be used in JSX, giving this error:
```
Error:(105, 17) TS2605:JSX element type 'LocalForm' is not a constructor function for JSX elements.
Types of property 'state' are incompatible.
Type 'void' is not assignable to type 'Readonly<{}>'.
```

Fix void type parameter in LocalForm definition

---

docs/guides/react-native.md
src/native.js

This PR adds some examples for Inputs and Pickers for React Native. It also shows how to use Picker.Items in the standard native Control.Picker. I'm not certain my code examples are entirely correct, particularly as concerns the `getTextValue` function. Please review.

Improve React Native Form and Control implementations

---

react-redux-form.d.ts

just add one line
react-redux-form.d.ts
`static button: React.ComponentClass<ControlProps<HTMLButtonElement>>;`
button is defined
https://github.com/davidkpiano/react-redux-form/blob/master/docs/api/Control.md
but definition doesn't have `Control.button`

typescript definition, add static Control.button property

---

src/android.js

David,
It was almost to easy... Just removed the IOS specific components and checked for any errors. I also noticed that you import 'MapView' but MapView has been deprecated: https://github.com/facebook/react-native/pull/10500. Wouldn't this cause errors? I don't have an IOS device yet to test.
I'm still pretty new with all of this so if you have any pointers/tips/advice it's appreciated :smile: . Anyway, I'll be using this for Android and IOS so perhaps I'll spot some bugs along the way.
Thanks, J

First draft Android support for React-Redux-Form.

---

react-redux-form.d.ts

I add `className?: string` to ErrorProps only
it's currently supported but definition and [doc](https://github.com/davidkpiano/react-redux-form/blob/master/docs/api/Errors.md), both has missed
so
someone who can write english, need to update `Erros.md`

Error Component has className props but definition isn't

---

src/actions/model-actions.js
test/actions-spec.js

The actions.xor function was using spread operator for an array concatenation when an item doesn't exist in the model value and it's a not correct behaviour when Immutable.js is used. I wrote a small fix and test case for the defaultStrategy version. Unfortunately I don't feel capable of writing actions test with Immutable.js support.

Immutable support in actions.xor

---

.gitignore
src/actions/model-actions.js
src/components/control-component.js
src/constants/control-props-map.js
test/control-component-spec.js

This makes defaultChecked work as expected, populating the model properly and everything. Also added some failing tests for the bug, and then made the tests pass.
Minor largely irrelevant changes, I use IDEA as my IDE, and I needed to .gitignore its files.
Also, in debugging, I found that areOwnPropsEqual and areStatePropsEqual had a different signature than assumed, which was lightly confusing, so I fixed the signature. Finally, "modelValue" was set in the return function, which I edited to make it so that I could variable-inspect it, but then decided to leave it in the end, because it followed the format of all the other return values, and I felt dirty setting it back.
Actual meat and potatoes are in "src/actions/model-actions.js" and "src/constants/control-props-map.js", which, are, …

Resolve Issue 905, defaultChecked bug on Control.checkbox

---

src/components/control-component.js
src/components/control-strip-defaults-component.js
src/constants/control-props-map.js
test/control-strip-defaults-component-spec.js
test/custom-control-component-spec.js
test/field-component-spec.js
test/form-component-spec.js

This fixes warning messages that were annoying and confusing me in my personal project about "defaultChecked" being set at the same time as "checked" is set, mostly, they also appeared in the console error log when running the unit tests. So I fixed those ones, and then got carried away and solved all of the warnings in the unit tests. The following error/warning messages were resolved:
```
Warning: Control contains an input of type checkbox with both checked and defaultChecked props. Input elements must be either controlled or uncontrolled (specify either the checked prop, or the defaultChecked prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components
Warning: Each child in an …
```

Minor fixes in console errors when running unit tests

---

src/reducers/form-actions-reducer.js
test/form-reducer-actions-spec.js

It is often nice to disable form fields while submission is pending, this currently requires trying to find the form and manually pass that down to field components. 
However since `submitted` and `submitFailed` propagate to subfields it would be convenient if `pending` did also.

setPending should update subFields

---

src/reducers/form-actions-reducer.js

When validity is a boolean and true, then `Object.keys` will be called on a boolean which will cause errors in IE. This change is meant to be equivalent to the existing code, but makes sure that `Object.keys` is not called on `validity` when it is a boolean. 
This appears to fix this issue: https://github.com/davidkpiano/react-redux-form/issues/806
Adding the ES6 shim fixes this issue because it returns an empty array when a boolean is passed into `Object.keys`, but users should not be required to add this shim in order to avoid this issue.

Preventing Object.keys from being called on a boolean

---

docs/guides/immutable.md

For an hour or so I was wondering why my form validators and onSubmit function were returning undefined when accessing attributes e.g. `formObj.name`. Turns out, when using the immutable counterparts, things are returned as `Map`. 
Added `formObj.get('name');` so people will get a hint that it works that way.

Update Immutable docs

---

src/reducers/form-actions-reducer.js

This change: https://github.com/davidkpiano/react-redux-form/commit/8a2d27b7df1bb3142ed540671ecaceeac2691451 makes it so Object.keys is not called on a boolean, but it now allows undefined through instead.
This PR should handle all three cases correctly (undefined, boolean, object)

Fix bug with validation on change where Object.keys called on undefined

---

docs/api/Control.md
src/components/control-component.js
test/custom-control-component-spec.js

This PR does as it says and adds `fieldValue` to the mapped props when the `withFieldValue` prop on a `Control` is `true`. This allows for child components that can behave dynamically based on the field's state.
Closes #967

Added fieldValue to mapped props when withFieldValue provided to Control

---

src/components/control-component.js
test/control-component-spec.js

It turns out, that when `validateOn !== 'change'` or when there is no validators, control component never cleared `reset` intent. This, in turn, means that when `updateOn !== 'change'` is set, control cannot be changed by user.
I've fixed this by always clearing the intent.
Fixes #982.
Feel free to suggest test improvements, I'm not sure this is currently done in optimal way. Should we check that text input is cleared instead (and is changeable by user after that)?

Fixed reset intent clearing bug

---

src/components/errors-component.js

The `Errors` component would issue a proptype warning when passing an
element as the message, despite happily rendering it. Changing it to
from `string` to `node` will allow rendering renderable things without
throwing proptype warnings.
Fixes #989

Allow nodes for the value of messages

---

package-lock.json
package.json
yarn.lock

shallow-compare 1.2.1 has a peer dependency on React 15. It is recently updated in 1.2.2 https://www.npmjs.com/package/shallow-compare which removes this dependency.
Currently RRF has an exact dependency on shallow-compare 1.2.1.
this PR updates the version to 1.2.2
https://github.com/davidkpiano/react-redux-form/issues/987

update shallow-compare to 1.2.2 for React 16 compat

---

src/actions/model-actions.js
src/components/control-component.js
src/components/field-component.js
test/field-formatter-spec.js

This PR is meant to resolve #745.
*Design*
This functionality allows a function to be passed in as a formatter (in much the same way as parsers work).  This formatter should expect as an input the form's model value, and is expected to transform that value into the way it should look on the input field.
As an example:
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import { Control, Errors } from 'react-redux-form';
const MonthYearInput = ({ name, ...rest }) => {
// Converts a raw MMYY string into a more pretty "MM / YY" string
const myFormatter = (val) => {
const month = val.substring(0, 2);
const year = val.substring(2, 4);
return `${month} / ${year}`;
};
// Removes all of the non-numeric characters from "MM / YY", and limits the value to four chars
const …
```

Adding in formatter functionality

---

src/utils/get-form-value.js
src/utils/to-array.js

I've got problem described in #726 while searching a possible solution for #729 I've noticed that change-action-reducer can remove specific keys if `removeKeys` specified in the change action. But it still works incorrectly if array field mutates to object.

Prevent changing values from array type to object

---

src/reducers/form-actions-reducer.js
test/field-actions-spec.js

#1006 
The investigation documented in #1006 makes clear that several functions are called in the whole process of "setting initial state". Of these, the only one I could find that only had one consumer was `setInitialFieldState`. It seems ideal that to choose to modify this function (if doing so can lead to a fix) so as to reduce the probability of regressions.
The function returned by `setInitialFieldState` used to accept two arguments, `val` and `key`. The `key` argument was (as far as I can tell) not being used in the (originally) intended way. Previously there was a code path for when `key === '$form'`. However, the only direct consumer of this function (`updateFields`, which can receive this function as `newState` or `newSubState`) would _never_ pass a string for `key`. Instead, it …

Fix setInitial form state shape malformation (#1006)

---

react-redux-form.d.ts

interface _FieldState does not contain a submitFailed property.

Update FieldState interface in type definition file

---

docs/guides/react-native.md
package.json
src/native.js
yarn.lock

Added in Control properties that were available on iOS but not Android: Control.DatePickerAndroid (ReactNative.DatePickerAndroid) and Control.SegmentedControlAndroid (`react-native-segmented-control-tab`)
Added these pretty quickly and I've not run the code, but all tests are passing.
Control.DatePickerAndroid isn't a component, might be better to make it a component to keep Control consistent.
Control.SegmentedControlAndroid uses the third-party package `react-native-segmented-control-tab`. @davidkpiano you may want to check out the package to see it's up to your standards :-).
I haven't used this package (yet), so apologies if I've missed something fundamental. Also sorry I wasn't able to test the new features; I'm at work at the moment and likely to be busy this evening. If someone is …

Control component feature parity between Android and iOS

---

src/components/control-component-factory.js

This line throw error intents is undefined when render FieldSet of checkboxes in custom Control component.
@davidkpiano, pls, merge and publish this ASAP

Fix for Safari on macOS and iOS

---

docs/api/actions.md

The definitions for `pristine` and `untouched` in the actions docs were the same:
```
The "pristine" state indicates that the user has not interacted with this field model yet.
...
An "untouched" field indicates that this model has not been interacted with yet.
```
I edited the definitions to match my understanding of the difference.

Clarify difference between pristine and untouched

---

src/components/control-component-factory.js

Blurring before updates are finished causes the field to have a touched state but not have the latest value.
If a error handler only shows error if a field has been touched, the error message will be visible for the duration of the debounce before disappearing.

Flush updates before blur if Control is debounceable

---

react-redux-form.d.ts

Allow to return JSX from messages object
If I understood correctly, there is no restriction on messages object value, so you can return string or any other JSX elements:
https://github.com/davidkpiano/react-redux-form/blob/master/src/components/errors-component.js#L33

Update typings for error messages prop

---

react-redux-form.d.ts

As stated in https://davidkpiano.github.io/react-redux-form/docs/api/Control.html the getValue function receives the value itself or event.target.value.

Improve getValue typing

---

src/components/control-component-factory.js
src/components/control-strip-defaults-component.js

Thank you for this library!   I've been getting an uncontrolled input warning on changing input fields and found a fix by providing a fallback to empty string when value is undefined.
Possibly a duplicate of #739, #714, and #630.

Fix uncontrolled input warning

---

src/components/control-component-factory.js

I passed in the wrong args in 0f4051206c4964648a9fde1215172615504e1d80. This fixes https://github.com/davidkpiano/react-redux-form/issues/1146. (haven't tested https://github.com/davidkpiano/react-redux-form/issues/1126)

fix onBlur returning empty synthetic event

---

src/components/control-component-factory.js

This reverts the change in #1151. Control should not determine what type the value should be. Control needs to return the value as is.
See discussion here: https://github.com/davidkpiano/react-redux-form/commit/ca5dda45ea3599aacb0db60a7e2a6cedf71f1079#r29259155

Revert defaulting control value to a string

---

src/native.js

So instead of doing `import { createForms } from 'react-redux-form/native'` I had to import it from `'react-redux-form/lib/reducers/forms-reducer'` which is not optimal

FIX - createForms was not exported for react-native

---

src/components/form-component.js
src/utils/get-form.js
test/form-component-spec.js

Fixes the issue described here - https://github.com/davidkpiano/react-redux-form/issues/924
Without understanding the internals in too much depth, it looks like `formStateKeyCache` was introduced as a way to track which parent form relationships for the models provided on `Field` attributes, in a way that would allow both `Fields` and `Forms` to use that `get-form` utility class.
Where this seems to break down is that for form-level models that aren't present at initialization, they never get the proper form structure in redux.
This PR addresses that by resetting the cached data form the provided model string, but only within the form component, and only when the state is being mapped to that model initially.

924 form cache clearing

---

src/reducers/forms-reducer.js

I don't know why nobody faced this problem from the beginning but I found it today in createForms. 
While passing entire reducer function whose initial state is an immutable Map, this initial state is not being converted into plain JS object because the strategy was not used there but if we provide the immutable or non-immutable structure as formValue, they are perfectly being converted into plain JS object.
```
import { fromJS } from 'immutable';
import { createForms } from 'react-redux-form/immutable';
// Its a multistep form
const initialState = fromJS({
basicDetails: {
firstName: ''
},
corpDetails: {
companyName: ''
}
});
const userReducer = function(state = initialState, action) {
return state;
}
const reducers = combineReducers({
foo: fooReducer,
...createForms({
user: userReducer …
```

Made the usage of immutable strategy in createForms

---

src/components/errors-component.js

When updating to react-native@0.57, I get an error because of bad proptype for wrapper.
In ReactNative, the Error component gets a View wrapper by default.
When View get a `function` type in react-native@0.50 it gets an `object` type in react-native@0.57 which give me an error.
I'm not sure it's the only component which will have the problem.

FIX - in react@16.5 ReactNative View is an Object

---

src/components/control-component-factory.js

I noticed that when there are two or more asyncValidators, the last one calling `done()` overwrote the results of all validators that finished before.
The reason was that `fieldValue` was captured when the validators were kicked off, and then merged at `done()` (`outerDone()` in the code), even if they had changed.
This also resolves #1013.

Fix async validators capturing and overwriting validation results

---

react-redux-form.d.ts

removed boolean and string from definitions for setFieldsValidity and setFieldsErrors, because form-actions-reducer.js uses map and outdated definitions are confusing

fix typescript definitions for setFieldsValidity and setFieldsErrors

---

src/components/control-component-factory.js
src/components/field-component.js

@davidkpiano 
as explained on #986 arrays can be used to specify a model on fields, this adds array proptype to field and control to prevent a warning.

added array as allowed propType for control/field

---

src/components/control-component-factory.js
src/components/form-component.js

This runs `npx react-codemod rename-unsafe-lifecycles` to replace unsafe methods

Fix deprecated react lifecycle methods

---

src/components/control-component-factory.js
src/components/form-component.js
test/form-component-spec.js
yarn.lock

Clearing the cache on `mapStateToProps` causes performance issues for applications using a large redux store.
This defers the clearing to `componentDidMount`.
I confirmed that all of the tests that were added to initially test clearing the cache are still working:
https://github.com/davidkpiano/react-redux-form/pull/1184/files#diff-55bc9da456e5c128d620d4d263cb75b3R2046

Clear form cache on `componentDidMount` instead of `mapStateToProps` (#1218)
